export const recipes = {
  data: {
    results: [
      {
        id: 634006,
        title: 'Banana Bread',
        image: 'https://spoonacular.com/recipeImages/634006-312x231.jpg',
        imageType: 'jpg',
      },
      {
        id: 634171,
        title: 'Banana Pudding Cake',
        image: 'https://spoonacular.com/recipeImages/634171-312x231.jpg',
        imageType: 'jpg',
      },
    ],
  },
}

export const recipe = {
  extendedIngredients: [
    {
      id: 18369,
      aisle: 'Baking',
      image: 'white-powder.jpg',
      consistency: 'SOLID',
      name: 'baking powder',
      nameClean: 'baking powder',
      original: '1/4 teaspoon baking powder',
      originalName: 'baking powder',
      amount: 0.25,
      unit: 'teaspoon',
      meta: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
        metric: {
          amount: 0.25,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
      },
    },
    {
      id: 18372,
      aisle: 'Baking',
      image: 'white-powder.jpg',
      consistency: 'SOLID',
      name: 'baking soda',
      nameClean: 'baking soda',
      original: '1/2 teaspoon baking soda',
      originalName: 'baking soda',
      amount: 0.5,
      unit: 'teaspoon',
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
        metric: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
      },
    },
    {
      id: 1009040,
      aisle: 'Produce',
      image: 'bananas.jpg',
      consistency: 'SOLID',
      name: 'bananas',
      nameClean: 'mashed banana',
      original: '2 mashed bananas',
      originalName: 'mashed bananas',
      amount: 2.0,
      unit: '',
      meta: ['mashed'],
      measures: {
        us: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
        metric: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
      },
    },
    {
      id: 1230,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'buttermilk.jpg',
      consistency: 'SOLID',
      name: 'buttermilk',
      nameClean: 'buttermilk',
      original: '1 cup Buttermilk or sour milk',
      originalName: 'Buttermilk or sour milk',
      amount: 1.0,
      unit: 'cup',
      meta: ['sour'],
      measures: {
        us: {
          amount: 1.0,
          unitShort: 'cup',
          unitLong: 'cup',
        },
        metric: {
          amount: 236.588,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 1123,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'egg.png',
      consistency: 'SOLID',
      name: 'eggs',
      nameClean: 'egg',
      original: '2 eggs',
      originalName: 'eggs',
      amount: 2.0,
      unit: '',
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
        metric: {
          amount: 2.0,
          unitShort: '',
          unitLong: '',
        },
      },
    },
    {
      id: 20081,
      aisle: 'Baking',
      image: 'flour.png',
      consistency: 'SOLID',
      name: 'flour',
      nameClean: 'wheat flour',
      original: '1 1/2 cups flour',
      originalName: 'flour',
      amount: 1.5,
      unit: 'cups',
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 354.882,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 19335,
      aisle: 'Baking',
      image: 'sugar-in-bowl.png',
      consistency: 'SOLID',
      name: 'sugar',
      nameClean: 'sugar',
      original: '1 1/8 cups sugar',
      originalName: 'sugar',
      amount: 1.125,
      unit: 'cups',
      meta: [],
      measures: {
        us: {
          amount: 1.125,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 266.161,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 1052050,
      aisle: 'Baking',
      image: 'vanilla.jpg',
      consistency: 'SOLID',
      name: 'vanilla',
      nameClean: 'vanilla',
      original: '1 teaspoon vanilla',
      originalName: 'vanilla',
      amount: 1.0,
      unit: 'teaspoon',
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
        metric: {
          amount: 1.0,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
      },
    },
    {
      id: 4669,
      aisle: 'Oil, Vinegar, Salad Dressing',
      image: 'vegetable-oil.jpg',
      consistency: 'LIQUID',
      name: 'vegetable oil',
      nameClean: 'vegetable oil',
      original: '2 tablespoons Vegetable oil',
      originalName: 'Vegetable oil',
      amount: 2.0,
      unit: 'tablespoons',
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
        metric: {
          amount: 2.0,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
      },
    },
    {
      id: 10112155,
      aisle: 'Nuts;Savory Snacks;Baking',
      image: 'walnuts.jpg',
      consistency: 'SOLID',
      name: 'walnuts',
      nameClean: 'walnut pieces',
      original: '1/4 cup chopped walnuts',
      originalName: 'chopped walnuts',
      amount: 0.25,
      unit: 'cup',
      meta: ['chopped'],
      measures: {
        us: {
          amount: 0.25,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 59.147,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
  ],
  id: 634202,
  title: 'Banana Walnut Cake',
  image: 'https://spoonacular.com/recipeImages/634202-556x370.jpg',
  analyzedInstructions: [
    {
      name: "Here's the recipe for the banana walnut cake (its very easy and good!)",
      steps: [
        {
          number: 1,
          step: 'Mix everything in the same bowl (using a wisk to make smooth)',
          ingredients: [],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
          ],
        },
        {
          number: 2,
          step: "Bake in a 9X13 inch pan (greased) at 350F for approx 35 minutes or until the top is brown and springs back when touched. This cake is quite sweet and doesn't need frosting. PS: to make sour milk (don't use old milk), put a tablespoon of vinegar in a cup of milk)/CAKES",
          ingredients: [
            {
              id: 1001077,
              name: 'soured milk',
              localizedName: 'soured milk',
              image: 'milk.png',
            },
            {
              id: 19230,
              name: 'frosting',
              localizedName: 'frosting',
              image: 'vanilla-frosting.png',
            },
            {
              id: 2053,
              name: 'vinegar',
              localizedName: 'vinegar',
              image: 'vinegar-(white).jpg',
            },
            {
              id: 1077,
              name: 'milk',
              localizedName: 'milk',
              image: 'milk.png',
            },
          ],
          equipment: [
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
              temperature: {
                number: 350.0,
                unit: 'Fahrenheit',
              },
            },
            {
              id: 404645,
              name: 'frying pan',
              localizedName: 'frying pan',
              image: 'pan.png',
            },
          ],
          length: {
            number: 35,
            unit: 'minutes',
          },
        },
      ],
    },
  ],
}
